name: CI

on:
  pull_request:


jobs:
  ci:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file:
          - tesla-ble-m5stack-atoms3.yml
          - tesla-ble-m5stack-nanoc6.yml
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Mock secrets.yaml from example
        run: cp secrets.yaml.example secrets.yaml
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v3.2.0
        with:
          yaml_file: ${{ matrix.file }}
          cache: true
